Add typing definitions and add usage in modules - mainly for documentaion purposes
datavaluepeople/kotsu pull request #14
Opened 2021-07-31 16:40 UTC by DBCerigo

2021-08-02 13:01 UTC, andrewsutjahjo approved these changes
Nice one, only a nitpick on the documentation side

2021-08-02 13:01 UTC, andrewsutjahjo commented on kotsu/typing.py
> +# Model's within kostu are not constrained in any way. It is up to the user to write Model's that
nit: plural of Model is Models

2021-08-08 17:55 UTC, ali-tny requested changes
looks great - just requesting changes cause I think we should also type the Registries with these new classes (which would make the inline typehints on line 36/37 of `kotsu/run.py` unnecessary), whis is a perfect use case for [Generic types](https://mypy.readthedocs.io/en/stable/generics.html)

2021-08-08 17:55 UTC, ali-tny commented on kotsu/typing.py
> +Validation = Callable[[Any], Results]
🐼  `Validation = Callable[[Model], Results]`

2021-08-13 12:58 UTC, benjamincerigo approved these changes
Yeah this look much clearer. 

Nice one.

2021-09-09 10:53 UTC, DBCerigo commented on kotsu/typing.py
> +# Model's within kostu are not constrained in any way. It is up to the user to write Model's that
40011cb

2021-09-09 11:03 UTC, DBCerigo commented on kotsu/typing.py
> +Validation = Callable[[Any], Results]
d88c564

2021-09-09 13:30 UTC, DBCerigo commented
@ali-tny I had a stab at the `Generic` - seems like I did it right, but I tried adding in some incorrect type hinting (like swapping `Validation` for `Model` in some function sigs in `run` module) but `mypy` didn't throw anything :/ Guess there's a lot of `Any` going about so. In any case, if you could quick review it, and check you think I did it right at least, that would be appreciated thanks!

2021-09-09 14:10 UTC, ali-tny approved these changes
looks great! nice one

re efficacy - yeah the Model stuff is never gonna catch much cause Model is Any, so we don't care what the type is - but it is doing work on the Validation, given that you don't have to manually type the validation on line 36 of run. if you set change it to `Validation = str` in the typing file, you'll see a mypy error for line 61 of run (the only place where the validation is actually called!), showing that the type of Validation (as a callable) is correctly tracked through. Likewise if the signature of a validation was untyped or typed differently to required, it'll complain

2021-09-09 14:22 UTC, DBCerigo commented
> looks great! nice one
> 
> re efficacy - yeah the Model stuff is never gonna catch much cause Model is Any, so we don't care what the type is - but it is doing work on the Validation, given that you don't have to manually type the validation on line 36 of run. if you set change it to `Validation = str` in the typing file, you'll see a mypy error for line 61 of run (the only place where the validation is actually called!), showing that the type of Validation (as a callable) is correctly tracked through. Likewise if the signature of a validation was untyped or typed differently to required, it'll complain

Nice nice. Lol I guess doing `validation: Model = ...` when `Model = Any` isn't going to throw much... derp. 

Thanks for the learnings and the reviews

2021-09-09 14:23 UTC, merged